"""Initial migration

Revision ID: 4ef976fcc10a
Revises: 
Create Date: 2025-01-21 17:43:10.904325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef976fcc10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sign_up_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('signup_date')

    with op.batch_alter_table('volunteer_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_event', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.drop_column('image_file')

    with op.batch_alter_table('user_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('sign_up_date')

    # ### end Alembic commands ###
