"""Add attended column to UserVolunteer

Revision ID: 55abdd46825f
Revises: e7780a07eab0
Create Date: 2025-01-24 00:30:49.892738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55abdd46825f'
down_revision = 'e7780a07eab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attended', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    with op.batch_alter_table('volunteer_event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_event', schema=None) as batch_op:
        batch_op.alter_column('image_file',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    with op.batch_alter_table('user_volunteer', schema=None) as batch_op:
        batch_op.drop_column('attended')

    # ### end Alembic commands ###
