"""Rename country to allergens

Revision ID: 6474afc3fd42
Revises: 
Create Date: 2025-01-24 21:45:45.428563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6474afc3fd42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop the existing Product table
    op.drop_table('product')

    # Recreate the Product table with updated schema
    op.create_table(
        'product',
        sa.Column('id', sa.Integer, primary_key=True, nullable=False),
        sa.Column('name', sa.String(40), nullable=False),
        sa.Column('description', sa.String(1000), nullable=False),
        sa.Column('category', sa.String(80), nullable=False),
        sa.Column('allergens', sa.String(200), nullable=True),  # New allergens column
        sa.Column('price', sa.Float, nullable=False),
        sa.Column('image_file', sa.String(20), nullable=False, default='default.jpg'),
        sa.Column('stock', sa.Integer, nullable=False, default=0),
        sa.Column('isValid', sa.Integer, nullable=False, default=1)
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('issue', sa.INTEGER(), nullable=False),
    sa.Column('feedback_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer, primary_key=True, nullable=False),
    sa.Column('name', sa.String(40), nullable=False),
    sa.Column('description', sa.String(1000), nullable=False),
    sa.Column('category', sa.String(80), nullable=False),
    sa.Column('country', sa.String(80), nullable=False),  # Old country column
    sa.Column('price', sa.Float, nullable=False),
    sa.Column('image_file', sa.String(20), nullable=False, default='default.jpg'),
    sa.Column('stock', sa.Integer, nullable=False, default=0),
    sa.Column('isValid', sa.Integer, nullable=False, default=1)
    )
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('credit', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('redeem_date', sa.DATE(), nullable=False),
    sa.Column('expiry_date', sa.DATE(), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('isValid', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redeemed_vouchers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('voucher_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voucher_id'], ['voucher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('orderstock', sa.INTEGER(), nullable=False),
    sa.Column('date_ordered', sa.VARCHAR(length=60), nullable=False),
    sa.Column('date_decision', sa.VARCHAR(length=60), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=8), nullable=False),
    sa.Column('company', sa.VARCHAR(length=80), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('country', sa.VARCHAR(length=80), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('isValid', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=8), nullable=False),
    sa.Column('address', sa.VARCHAR(length=80), nullable=False),
    sa.Column('secretQn', sa.VARCHAR(length=80), nullable=False),
    sa.Column('isAdmin', sa.BOOLEAN(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('credit', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
